[package]
name = "deepseek-harness-desktop"
version = "1.1.1"
description = "DeepSeek Harness Desktop Tauri shell"
authors = ["XLCYun"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-opener = "2.5.4"
tauri-plugin-clipboard-manager = "2.3.2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
